////////////////////////////////////////
// when set to private  - privateAudio plays if assigned.  allows outgoing calls to contacts without privateAudio. unsaved numbers play standard audio.
// when set to public - publicAudio plays if assigned. all other outgoing calls are allowed.
////////////////////////////////////////
var environmentStatus = "private";

var contacts =[

////////////////////////////////////////
// TEMP CONTACTS (ADD/REMOVE FROM ICLOUD AND GSHEET WHEN FINALIZING)
////////////////////////////////////////
/*IN INCLOUD*/{name: 'Prakash Poudel', telNumber: '4435652738', caption: '', textColor: 'black', display: false, privateAudio: 'busy', publicAudio: '', },

////////////////////////////////////////
// 911 (NOT DISPLAYED)
////////////////////////////////////////
{name: '911', telNumber: '911', caption: '', textColor: 'black', display: false, privateAudio: 'busy', publicAudio: '', },

////////////////////////////////////////
// DECOY CONTACTS (NOT IN ICLOUD. IF NEED TO ALLOW TRUE CONTACT DURING environmentStatus = "public" - TEMPORARILY SET publicAudio TO '')
////////////////////////////////////////
{name: 'Voicemail Box', telNumber: '3018062639', caption: '', textColor: 'black', display: false, privateAudio: 'vmBox', publicAudio: 'vmBox', },
{name: 'USPS', telNumber: '4103814373', caption: '', textColor: 'black', display: false, privateAudio: 'usps', publicAudio: 'busy', },
{name: 'Howard County Library', telNumber: '4103137700', caption: '', textColor: 'black', display: false, privateAudio: 'hcLibrary', publicAudio: 'busy', },
{name: 'Bain Center', telNumber: '4103137213', caption: '', textColor: 'black', display: false, privateAudio: 'bain', publicAudio: 'busy', },
{name: 'CAP1 main', telNumber: '18773834802', caption: '', textColor: 'black', display: false, privateAudio: 'cap1', publicAudio: 'busy', },
{name: 'CAP1 clarskville', telNumber: '4105311788', caption: '', textColor: 'black', display: false, privateAudio: 'cap1', publicAudio: 'busy', },
{name: 'CAP1 elkridge', telNumber: '4108722770', caption: '', textColor: 'black', display: false, privateAudio: 'cap1', publicAudio: 'busy', },
{name: 'CAP1 burtonsville', telNumber: '3014768789', caption: '', textColor: 'black', display: false, privateAudio: 'cap1', publicAudio: 'busy', },
{name: 'CAP1 laurel', telNumber: '3014976923', caption: '', textColor: 'black', display: false, privateAudio: 'cap1', publicAudio: 'busy', },
{name: 'CIT', telNumber: '8554622652', caption: '', textColor: 'black', display: false, privateAudio: 'cit', publicAudio: 'busy', },
{name: 'PNC main', telNumber: '18887622265', caption: '', textColor: 'black', display: false, privateAudio: 'pnc', publicAudio: 'busy', },
{name: 'PNC columbia', telNumber: '4108729180', caption: '', textColor: 'black', display: false, privateAudio: 'pnc', publicAudio: 'busy', },
{name: 'PNC clarksville', telNumber: '4105312113', caption: '', textColor: 'black', display: false, privateAudio: 'pnc', publicAudio: 'busy', },
{name: 'PNC fulton', telNumber: '3014906050', caption: '', textColor: 'black', display: false, privateAudio: 'pnc', publicAudio: 'busy', },
{name: 'PNC long gate', telNumber: '4104658979', caption: '', textColor: 'black', display: false, privateAudio: 'pnc', publicAudio: 'busy', },
{name: 'PNC rogers ave', telNumber: '4107503800', caption: '', textColor: 'black', display: false, privateAudio: 'pnc', publicAudio: 'busy', },
{name: 'MTB main', telNumber: '18007242440', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB banking', telNumber: '18007909130', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB columbia mall', telNumber: '4107401449', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB kings contrivance', telNumber: '4107401513', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB clarksville', telNumber: '4105317083', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB dobbin', telNumber: '4109646843', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB executive park', telNumber: '4107300125', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB bethany', telNumber: '4104652409', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MTB st johns', telNumber: '4104651628', caption: '', textColor: 'black', display: false, privateAudio: 'mtb', publicAudio: 'busy', },
{name: 'MVA', telNumber: '18009501682', caption: '', textColor: 'black', display: false, privateAudio: 'mva', publicAudio: 'busy', },
{name: 'MVA', telNumber: '4107687000', caption: '', textColor: 'black', display: false, privateAudio: 'mva', publicAudio: 'busy', },
{name: 'Passport Office', telNumber: '18774872778', caption: '', textColor: 'black', display: false, privateAudio: 'passport', publicAudio: 'busy', },
{name: 'Passport Office', telNumber: '8888747793', caption: '', textColor: 'black', display: false, privateAudio: 'passport', publicAudio: 'busy', },
{name: 'Rush My Passport', telNumber: '8002201899', caption: '', textColor: 'black', display: false, privateAudio: 'rush my passport', publicAudio: 'busy', },
{name: 'Rush My Passport', telNumber: '8775039838', caption: '', textColor: 'black', display: false, privateAudio: 'rush my passport', publicAudio: 'busy', },
{name: 'Passport World', telNumber: '9364940894', caption: '', textColor: 'black', display: false, privateAudio: 'passport world', publicAudio: 'busy', },
{name: 'CheapOair', telNumber: '6467384845', caption: '', textColor: 'black', display: false, privateAudio: 'cheapoair', publicAudio: 'busy', },
{name: 'CheapOair', telNumber: '6467384820', caption: '', textColor: 'black', display: false, privateAudio: 'cheapoair', publicAudio: 'busy', },
{name: 'CheapOair', telNumber: '8458480226', caption: '', textColor: 'black', display: false, privateAudio: 'cheapoair', publicAudio: 'busy', },
{name: 'CheapOair', telNumber: '6467384934', caption: '', textColor: 'black', display: false, privateAudio: 'cheapoair', publicAudio: 'busy', },
{name: 'CheapOair', telNumber: '8458480211', caption: '', textColor: 'black', display: false, privateAudio: 'cheapoair', publicAudio: 'busy', },
{name: 'CheapOair', telNumber: '6462376850', caption: '', textColor: 'black', display: false, privateAudio: 'cheapoair', publicAudio: 'busy', },
{name: 'Proxity', telNumber: '7575028951', caption: '', textColor: 'black', display: false, privateAudio: 'proxity', publicAudio: 'busy', },
{name: 'Proxity John', telNumber: '7575028952', caption: '', textColor: 'black', display: false, privateAudio: 'proxity', publicAudio: 'busy', },
{name: 'Proxity Lori', telNumber: '7573019994', caption: '', textColor: 'black', display: false, privateAudio: 'proxity', publicAudio: 'busy', },
{name: 'CIBT', telNumber: '8009292428', caption: '', textColor: 'black', display: false, privateAudio: 'CIBT', publicAudio: 'busy', },
{name: 'CIBT', telNumber: '8773048071', caption: '', textColor: 'black', display: false, privateAudio: 'CIBT', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '8008607940', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '8159647940', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '8159971628', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '8159975419', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '6085611544', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '8159971666', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore', telNumber: '8159975398', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore Christina', telNumber: '8472879051', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore Christina', telNumber: '8159971648', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore Christina', telNumber: '18778229286', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore Christina', telNumber: '3375370585', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'SuppyCore Christina', telNumber: '8159971651', caption: '', textColor: 'black', display: false, privateAudio: 'supplycore', publicAudio: 'busy', },
{name: 'Unicor', telNumber: '2023073198', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor El Reno', telNumber: '4052624875', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Nick Abshire', telNumber: '4053197708', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Chris Davis', telNumber: '4053197670', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Manchester', telNumber: '6065981900', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Atlanta', telNumber: '4046355100', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Craig Broadwater', telNumber: '8433879503', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Williamsburg', telNumber: '8433879400', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Latrell Green Office', telNumber: '2023053823', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Latrell Green Cell', telNumber: '2022093869', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },
{name: 'Unicor Yazoo City Low', telNumber: '6627514800', caption: '', textColor: 'black', display: false, privateAudio: 'unicor', publicAudio: 'busy', },

////////////////////////////////////////
// REAL CONTACTS
////////////////////////////////////////
{name: 'Adam Neighbor', telNumber: '2404613608', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Agarwal Accountant', telNumber: '3014045258', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Agarwal Son  Raj', telNumber: '3014959777', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Ajay - Tanu Father', telNumber: '7322599418', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Akshad Mom', telNumber: '7324040642', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Akshad Sagar Jan 21', telNumber: '7325937053', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Anil Khatri', telNumber: '4106089060', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Anju Canada', telNumber: '7057921510', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Barbar Shop', telNumber: '4435830880', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Bge Reduce Bill', telNumber: '4432768840', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Comcast', telNumber: '8002662278', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Dhruv Saren', telNumber: '7742533451', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Dimple Siddhu', telNumber: '5712633947', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Dixa Dolly', telNumber: '7743657575', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Dolly Cell. 10th August', telNumber: '7742531295', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Domonic Barnes And Noble', telNumber: '3018091552', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Dr Ochaney Mahesh April 16', telNumber: '4107684700', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'East Columbia', telNumber: '4103137680', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Floyds Barbershop', telNumber: '4435398720', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Geeta Didi. Anand Shahib', telNumber: '4105319579', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Geeta Didi. Anand Shahib', telNumber: '4438121630', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Gurdawra Silver Spring', telNumber: '3013842133', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Imtiaz Chowdhry', telNumber: '4109643611', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Jayesh', telNumber: '3092531405', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Madhu John Hopkins', telNumber: '4105507871', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Masala Bazar', telNumber: '4107159900', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Meals On Wheel', telNumber: '4435730942', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Meena Sharma', telNumber: '2408995482', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'MOVICO', telNumber: '4437558990', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Patient First Columbia', telNumber: '4437184067', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Patient First. Corporate Office', telNumber: '8049685700', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Pichanga', telNumber: '4104614266', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'PNC Codes', telNumber: '76200', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Preyinka Mom.  Suraj', telNumber: '4436189193', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Radiology Advanced', telNumber: '4434361600', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Rajender Gattu', telNumber: '7346526107', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Rajiv Rehani', telNumber: '3017288056', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Rams Fast Tax Service', telNumber: '3014451040', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Rema Gandhi', telNumber: '5088781498', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Risab. Shivaan Friend', telNumber: '7347316107', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Rishab Mom', telNumber: '7346528142', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Satish Kumar', telNumber: '2812076449', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Satish Kumar', telNumber: '8326930948', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Shilpa', telNumber: '2407235725', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Shivaan', telNumber: '3018064071', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Shyam Suni Husband', telNumber: '4438785431', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Sundesh', telNumber: '3013103795', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Sundesh Father Mohan', telNumber: '4108120314', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Suni Jani', telNumber: '4107074135', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Sunil Dr Dolly 30 Sept', telNumber: '5086156739', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Suraj Dad', telNumber: '2403372022', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Suraj Mom Pinki', telNumber: '4109601435', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'SURAJ SHIVAAN FRIEND', telNumber: '4109352786', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Surgen Office Mathew', telNumber: '4104486400', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Sushma Dr Pinki Sister', telNumber: '2023297774', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'T T Maha Abdin', telNumber: '4432552675', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'UPS Billing', telNumber: '9739444482', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Urgent Care Columbia', telNumber: '4102909990', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Vaibhav', telNumber: '7323518588', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Vaibhav Dad', telNumber: '7325700861', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },
{name: 'Wendys Rt 108', telNumber: '4435455464', caption: '', textColor: 'black', display: true, privateAudio: '', publicAudio: '', },

]

var calls = [

////////////////////////////////////////
// UNCOMMENT TO PROVE VOICEMAIL IS WORKING
////////////////////////////////////////
//{name: 'Shivaan', telNumber: '3018064071', caption: 'Today', textColor: 'red', voicemail: 'vmTest', checkDecoyRules: false, },

////////////////////////////////////////
// CALLS (if checkDecoyRules is false, call will go through. if true, checks rules for communication in contacts before connecting)
////////////////////////////////////////
{name: 'Dolly Cell. 10th August', telNumber: '7742531295', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Geeta Didi. Anand Shahib', telNumber: '4438121630', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: 'Few days ago', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Jayesh', telNumber: '3092531405', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Suraj Dad', telNumber: '2403372022', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Suraj Dad', telNumber: '2403372022', caption: 'Few days ago', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Suraj Dad', telNumber: '2403372022', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Rajiv Rehani', telNumber: '3017288056', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Vaibhav', telNumber: '7323518588', caption: 'Few days ago', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Vaibhav Dad', telNumber: '7325700861', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: 'Few days ago', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Vaibhav Dad', telNumber: '7325700861', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Sundesh', telNumber: '3013103795', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: 'Few days ago', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: 'Few days ago', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: 'Few days ago', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Sunil Dr Dolly 30 Sept', telNumber: '5086156739', caption: '', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Geeta Didi. Anand Shahib', telNumber: '4438121630', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Gurdawra Silver Spring', telNumber: '3013842133', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Gurdawra Silver Spring', telNumber: '3013842133', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: '', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Nandit Gandhi Jan 24rth', telNumber: '5084097856', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Shivaan', telNumber: '3018064071', caption: '', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Sunil Dr Dolly 30 Sept', telNumber: '5086156739', caption: '', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Sunil Dr Dolly 30 Sept', telNumber: '5086156739', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Rajiv Rehani', telNumber: '3017288056', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Rajiv Rehani', telNumber: '3017288056', caption: '', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Rajiv Rehani', telNumber: '3017288056', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Sundesh', telNumber: '3013103795', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Gurdawra Silver Spring', telNumber: '3013842133', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Dolly Cell. 10th August', telNumber: '7742531295', caption: '', textColor: 'red', voicemail: '', checkDecoyRules: false, },
{name: 'Dolly Cell. 10th August', telNumber: '7742531295', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Suraj Dad', telNumber: '2403372022', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },
{name: 'Rajiv Rehani', telNumber: '3017288056', caption: '', textColor: 'black', voicemail: '', checkDecoyRules: false, },

]
